using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public class ApiConstants
  {
    public uint MaxPhysicalDeviceNameSize = 256;

    public uint UuidSize = 16;

    public uint MaxExtensionNameSize = 256;

    public uint MaxDescriptionSize = 256;

    public uint MaxMemoryTypes = 32;

    public uint MaxMemoryHeaps = 16;

    public float LodClampNone = 1000.0f;

    public uint RemainingMipLevels = uint.MaxValue;

    public uint RemainingArrayLayers = uint.MaxValue;

    public ulong WholeSize = ulong.MaxValue;

    public uint AttachmentUnused = uint.MaxValue;

    public uint TRUE = 1;

    public uint FALSE = 0;

    public uint QueueFamilyIgnored = uint.MaxValue;

    public uint SubpassExternal = uint.MaxValue;
  }
}