namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum BlendFactor
  {
    BlendFactorZero = 0,

    BlendFactorOne = 1,

    BlendFactorSrcColor = 2,

    BlendFactorOneMinusSrcColor = 3,

    BlendFactorDstColor = 4,

    BlendFactorOneMinusDstColor = 5,

    BlendFactorSrcAlpha = 6,

    BlendFactorOneMinusSrcAlpha = 7,

    BlendFactorDstAlpha = 8,

    BlendFactorOneMinusDstAlpha = 9,

    BlendFactorConstantColor = 10,

    BlendFactorOneMinusConstantColor = 11,

    BlendFactorConstantAlpha = 12,

    BlendFactorOneMinusConstantAlpha = 13,

    BlendFactorSrcAlphaSaturate = 14,

    BlendFactorSrc1Color = 15,

    BlendFactorOneMinusSrc1Color = 16,

    BlendFactorSrc1Alpha = 17,

    BlendFactorOneMinusSrc1Alpha = 18
  }
}