namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum BorderColor
  {
    BorderColorFloatTransparentBlack = 0,

    BorderColorIntTransparentBlack = 1,

    BorderColorFloatOpaqueBlack = 2,

    BorderColorIntOpaqueBlack = 3,

    BorderColorFloatOpaqueWhite = 4,

    BorderColorIntOpaqueWhite = 5
  }
}