using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum ColorComponentFlags
  {
    COLOR_COMPONENT_R_BIT = 0,

    COLOR_COMPONENT_G_BIT = 1,

    COLOR_COMPONENT_B_BIT = 2,

    COLOR_COMPONENT_A_BIT = 3
  }
}