using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum CommandBufferResetFlags
  {
    /// <summary> 
    /// Release resources owned by the buffer
    /// </summary> 
    COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT = 0
  }
}