namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum ComponentSwizzle
  {
    COMPONENT_SWIZZLE_IDENTITY = 0,

    COMPONENT_SWIZZLE_ZERO = 1,

    COMPONENT_SWIZZLE_ONE = 2,

    COMPONENT_SWIZZLE_R = 3,

    COMPONENT_SWIZZLE_G = 4,

    COMPONENT_SWIZZLE_B = 5,

    COMPONENT_SWIZZLE_A = 6
  }
}