namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum CompareOp
  {
    CompareOpNever = 0,

    CompareOpLess = 1,

    CompareOpEqual = 2,

    CompareOpLessOrEqual = 3,

    CompareOpGreater = 4,

    CompareOpNotEqual = 5,

    CompareOpGreaterOrEqual = 6,

    CompareOpAlways = 7
  }
}