namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum ComponentSwizzle
  {
    ComponentSwizzleIdentity = 0,

    ComponentSwizzleZero = 1,

    ComponentSwizzleOne = 2,

    ComponentSwizzleR = 3,

    ComponentSwizzleG = 4,

    ComponentSwizzleB = 5,

    ComponentSwizzleA = 6
  }
}