using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum CompositeAlphaFlagBitsKHR
  {
    COMPOSITE_ALPHA_OPAQUE_BIT_KHR = 0,

    COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR = 1,

    COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR = 2,

    COMPOSITE_ALPHA_INHERIT_BIT_KHR = 3
  }
}