namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum CompareOp
  {
    COMPARE_OP_NEVER = 0,

    COMPARE_OP_LESS = 1,

    COMPARE_OP_EQUAL = 2,

    COMPARE_OP_LESS_OR_EQUAL = 3,

    COMPARE_OP_GREATER = 4,

    COMPARE_OP_NOT_EQUAL = 5,

    COMPARE_OP_GREATER_OR_EQUAL = 6,

    COMPARE_OP_ALWAYS = 7
  }
}