using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum CullModeFlags
  {
    CULL_MODE_NONE = 0,

    CULL_MODE_FRONT_BIT = 0,

    CULL_MODE_BACK_BIT = 1,

    CULL_MODE_FRONT_AND_BACK = 0x00000003
  }
}