using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum DebugReportFlagBitsEXT
  {
    DEBUG_REPORT_INFORMATION_BIT_EXT = 0,

    DEBUG_REPORT_WARNING_BIT_EXT = 1,

    DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT = 2,

    DEBUG_REPORT_ERROR_BIT_EXT = 3,

    DEBUG_REPORT_DEBUG_BIT_EXT = 4
  }
}