namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum DebugReportErrorEXT
  {
    DEBUG_REPORT_ERROR_NONE_EXT = 0,

    DEBUG_REPORT_ERROR_CALLBACK_REF_EXT = 1
  }
}