namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum DescriptorType
  {
    DescriptorTypeSampler = 0,

    DescriptorTypeCombinedImageSampler = 1,

    DescriptorTypeSampledImage = 2,

    DescriptorTypeStorageImage = 3,

    DescriptorTypeUniformTexelBuffer = 4,

    DescriptorTypeStorageTexelBuffer = 5,

    DescriptorTypeUniformBuffer = 6,

    DescriptorTypeStorageBuffer = 7,

    DescriptorTypeUniformBufferDynamic = 8,

    DescriptorTypeStorageBufferDynamic = 9,

    DescriptorTypeInputAttachment = 10
  }
}