using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum DescriptorPoolCreateFlags
  {
    /// <summary> 
    /// Descriptor sets may be freed individually
    /// </summary> 
    DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT = 0
  }
}