using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum DisplayPlaneAlphaFlagBitsKHR
  {
    DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR = 0,

    DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR = 1,

    DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR = 2,

    DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR = 3
  }
}