namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum ImageViewType
  {
    ImageViewType1D = 0,

    ImageViewType2D = 1,

    ImageViewType3D = 2,

    ImageViewTypeCube = 3,

    ImageViewType1DArray = 4,

    ImageViewType2DArray = 5,

    ImageViewTypeCubeArray = 6
  }
}