using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum ImageAspectFlags
  {
    IMAGE_ASPECT_COLOR_BIT = 0,

    IMAGE_ASPECT_DEPTH_BIT = 1,

    IMAGE_ASPECT_STENCIL_BIT = 2,

    IMAGE_ASPECT_METADATA_BIT = 3
  }
}