namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum ImageViewType
  {
    IMAGE_VIEW_TYPE_1D = 0,

    IMAGE_VIEW_TYPE_2D = 1,

    IMAGE_VIEW_TYPE_3D = 2,

    IMAGE_VIEW_TYPE_CUBE = 3,

    IMAGE_VIEW_TYPE_1D_ARRAY = 4,

    IMAGE_VIEW_TYPE_2D_ARRAY = 5,

    IMAGE_VIEW_TYPE_CUBE_ARRAY = 6
  }
}