namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum LogicOp
  {
    LogicOpClear = 0,

    LogicOpAnd = 1,

    LogicOpAndReverse = 2,

    LogicOpCopy = 3,

    LogicOpAndInverted = 4,

    LogicOpNoOp = 5,

    LogicOpXor = 6,

    LogicOpOr = 7,

    LogicOpNor = 8,

    LogicOpEquivalent = 9,

    LogicOpInvert = 10,

    LogicOpOrReverse = 11,

    LogicOpCopyInverted = 12,

    LogicOpOrInverted = 13,

    LogicOpNand = 14,

    LogicOpSet = 15
  }
}