namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum LogicOp
  {
    LOGIC_OP_CLEAR = 0,

    LOGIC_OP_AND = 1,

    LOGIC_OP_AND_REVERSE = 2,

    LOGIC_OP_COPY = 3,

    LOGIC_OP_AND_INVERTED = 4,

    LOGIC_OP_NO_OP = 5,

    LOGIC_OP_XOR = 6,

    LOGIC_OP_OR = 7,

    LOGIC_OP_NOR = 8,

    LOGIC_OP_EQUIVALENT = 9,

    LOGIC_OP_INVERT = 10,

    LOGIC_OP_OR_REVERSE = 11,

    LOGIC_OP_COPY_INVERTED = 12,

    LOGIC_OP_OR_INVERTED = 13,

    LOGIC_OP_NAND = 14,

    LOGIC_OP_SET = 15
  }
}