namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum PhysicalDeviceType
  {
    PHYSICAL_DEVICE_TYPE_OTHER = 0,

    PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU = 1,

    PHYSICAL_DEVICE_TYPE_DISCRETE_GPU = 2,

    PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU = 3,

    PHYSICAL_DEVICE_TYPE_CPU = 4
  }
}