namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum PresentModeKHR
  {
    PRESENT_MODE_IMMEDIATE_KHR = 0,

    PRESENT_MODE_MAILBOX_KHR = 1,

    PRESENT_MODE_FIFO_KHR = 2,

    PRESENT_MODE_FIFO_RELAXED_KHR = 3
  }
}