namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum PrimitiveTopology
  {
    PrimitiveTopologyPointList = 0,

    PrimitiveTopologyLineList = 1,

    PrimitiveTopologyLineStrip = 2,

    PrimitiveTopologyTriangleList = 3,

    PrimitiveTopologyTriangleStrip = 4,

    PrimitiveTopologyTriangleFan = 5,

    PrimitiveTopologyLineListWithAdjacency = 6,

    PrimitiveTopologyLineStripWithAdjacency = 7,

    PrimitiveTopologyTriangleListWithAdjacency = 8,

    PrimitiveTopologyTriangleStripWithAdjacency = 9,

    PrimitiveTopologyPatchList = 10
  }
}