using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum ShaderStageFlags
  {
    ShaderStageVertexBit = 0,

    ShaderStageTessellationControlBit = 1,

    ShaderStageTessellationEvaluationBit = 2,

    ShaderStageGeometryBit = 3,

    ShaderStageFragmentBit = 4,

    ShaderStageComputeBit = 5,

    ShaderStageAllGraphics = 0x0000001F,

    ShaderStageAll = 0x7FFFFFFF
  }
}