using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum SparseImageFormatFlags
  {
    /// <summary> 
    /// Image uses a single miptail region for all array layers
    /// </summary> 
    SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT = 0,

    /// <summary> 
    /// Image requires mip level dimensions to be an integer multiple of the sparse image block dimensions for non-miptail levels.
    /// </summary> 
    SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT = 1,

    /// <summary> 
    /// Image uses a non-standard sparse image block dimensions
    /// </summary> 
    SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT = 2
  }
}