namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum StencilOp
  {
    StencilOpKeep = 0,

    StencilOpZero = 1,

    StencilOpReplace = 2,

    StencilOpIncrementAndClamp = 3,

    StencilOpDecrementAndClamp = 4,

    StencilOpInvert = 5,

    StencilOpIncrementAndWrap = 6,

    StencilOpDecrementAndWrap = 7
  }
}