namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum StencilOp
  {
    STENCIL_OP_KEEP = 0,

    STENCIL_OP_ZERO = 1,

    STENCIL_OP_REPLACE = 2,

    STENCIL_OP_INCREMENT_AND_CLAMP = 3,

    STENCIL_OP_DECREMENT_AND_CLAMP = 4,

    STENCIL_OP_INVERT = 5,

    STENCIL_OP_INCREMENT_AND_WRAP = 6,

    STENCIL_OP_DECREMENT_AND_WRAP = 7
  }
}