namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// Structure type enumerant
  /// </summary>
  public enum StructureType
  {
    StructureTypeApplicationInfo = 0,

    StructureTypeInstanceCreateInfo = 1,

    StructureTypeDeviceQueueCreateInfo = 2,

    StructureTypeDeviceCreateInfo = 3,

    StructureTypeSubmitInfo = 4,

    StructureTypeMemoryAllocateInfo = 5,

    StructureTypeMappedMemoryRange = 6,

    StructureTypeBindSparseInfo = 7,

    StructureTypeFenceCreateInfo = 8,

    StructureTypeSemaphoreCreateInfo = 9,

    StructureTypeEventCreateInfo = 10,

    StructureTypeQueryPoolCreateInfo = 11,

    StructureTypeBufferCreateInfo = 12,

    StructureTypeBufferViewCreateInfo = 13,

    StructureTypeImageCreateInfo = 14,

    StructureTypeImageViewCreateInfo = 15,

    StructureTypeShaderModuleCreateInfo = 16,

    StructureTypePipelineCacheCreateInfo = 17,

    StructureTypePipelineShaderStageCreateInfo = 18,

    StructureTypePipelineVertexInputStateCreateInfo = 19,

    StructureTypePipelineInputAssemblyStateCreateInfo = 20,

    StructureTypePipelineTessellationStateCreateInfo = 21,

    StructureTypePipelineViewportStateCreateInfo = 22,

    StructureTypePipelineRasterizationStateCreateInfo = 23,

    StructureTypePipelineMultisampleStateCreateInfo = 24,

    StructureTypePipelineDepthStencilStateCreateInfo = 25,

    StructureTypePipelineColorBlendStateCreateInfo = 26,

    StructureTypePipelineDynamicStateCreateInfo = 27,

    StructureTypeGraphicsPipelineCreateInfo = 28,

    StructureTypeComputePipelineCreateInfo = 29,

    StructureTypePipelineLayoutCreateInfo = 30,

    StructureTypeSamplerCreateInfo = 31,

    StructureTypeDescriptorSetLayoutCreateInfo = 32,

    StructureTypeDescriptorPoolCreateInfo = 33,

    StructureTypeDescriptorSetAllocateInfo = 34,

    StructureTypeWriteDescriptorSet = 35,

    StructureTypeCopyDescriptorSet = 36,

    StructureTypeFramebufferCreateInfo = 37,

    StructureTypeRenderPassCreateInfo = 38,

    StructureTypeCommandPoolCreateInfo = 39,

    StructureTypeCommandBufferAllocateInfo = 40,

    StructureTypeCommandBufferInheritanceInfo = 41,

    StructureTypeCommandBufferBeginInfo = 42,

    StructureTypeRenderPassBeginInfo = 43,

    StructureTypeBufferMemoryBarrier = 44,

    StructureTypeImageMemoryBarrier = 45,

    StructureTypeMemoryBarrier = 46,

    StructureTypeLoaderInstanceCreateInfo = 47,

    StructureTypeLoaderDeviceCreateInfo = 48,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeSwapchainCreateInfoKhr = 1000001000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypePresentInfoKhr = 1000001001,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeDisplayModeCreateInfoKhr = 1000002000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeDisplaySurfaceCreateInfoKhr = 1000002001,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeDisplayPresentInfoKhr = 1000003000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeXlibSurfaceCreateInfoKhr = 1000004000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeXcbSurfaceCreateInfoKhr = 1000005000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeWaylandSurfaceCreateInfoKhr = 1000006000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeMirSurfaceCreateInfoKhr = 1000007000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeAndroidSurfaceCreateInfoKhr = 1000008000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeWin32SurfaceCreateInfoKhr = 1000009000,

    /// <summary> 
    /// Extension Enum Value
    /// </summary> 
    StructureTypeDebugReportCallbackCreateInfoExt = 1000011000
  }
}