using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum SurfaceTransformFlagBitsKHR
  {
    SURFACE_TRANSFORM_IDENTITY_BIT_KHR = 0,

    SURFACE_TRANSFORM_ROTATE_90_BIT_KHR = 1,

    SURFACE_TRANSFORM_ROTATE_180_BIT_KHR = 2,

    SURFACE_TRANSFORM_ROTATE_270_BIT_KHR = 3,

    SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR = 4,

    SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR = 5,

    SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR = 6,

    SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR = 7,

    SURFACE_TRANSFORM_INHERIT_BIT_KHR = 8
  }
}