using System;

namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  [Flags]
  public enum SurfaceTransformKhr
  {
    SurfaceTransformIdentityBitKhr = 0,

    SurfaceTransformRotate90BitKhr = 1,

    SurfaceTransformRotate180BitKhr = 2,

    SurfaceTransformRotate270BitKhr = 3,

    SurfaceTransformHorizontalMirrorBitKhr = 4,

    SurfaceTransformHorizontalMirrorRotate90BitKhr = 5,

    SurfaceTransformHorizontalMirrorRotate180BitKhr = 6,

    SurfaceTransformHorizontalMirrorRotate270BitKhr = 7,

    SurfaceTransformInheritBitKhr = 8
  }
}