namespace SixtenLabs.Spawn.Vulkan.Target
{
  /// <summary>
  /// *** Do Not Edit ***
  /// This file was generated by the Spawn Code Generator.
  /// https://github.com/SixtenLabs/Spawn
  /// 
  /// Generated from the vk.xml registry file from Khronos Group.
  /// https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml
  /// 
  /// </summary>
  public enum SystemAllocationScope
  {
    SYSTEM_ALLOCATION_SCOPE_COMMAND = 0,

    SYSTEM_ALLOCATION_SCOPE_OBJECT = 1,

    SYSTEM_ALLOCATION_SCOPE_CACHE = 2,

    SYSTEM_ALLOCATION_SCOPE_DEVICE = 3,

    SYSTEM_ALLOCATION_SCOPE_INSTANCE = 4
  }
}